CREATE DATABASE news_letter DEFAULT CHARACTER SET utf8mb4;
USE news_letter;

-- 1. Table internaute
CREATE TABLE internaute (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(50) DEFAULT NULL,
  prenom VARCHAR(50) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

-- 2. Table news
CREATE TABLE news (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  titre VARCHAR(255) DEFAULT NULL,
  resumee TEXT DEFAULT NULL,
  contenu TEXT DEFAULT NULL,
  date_publication TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

-- 3. Table suggestion
CREATE TABLE suggestion (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  type_suggestion VARCHAR(50) NOT NULL,
  contenu TEXT NOT NULL,
  date_soumission DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

-- 4. Table visiteur
CREATE TABLE visiteur (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(50) DEFAULT NULL,
  prenom VARCHAR(50) DEFAULT NULL,
  sexe VARCHAR(10) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
